print("Cálculo da área de um quadrilátero: ")
base = float(input("Entre com a base: "))
altura = float(input("Entre com a altura: "))
area = (base * altura)
print("A área do quadrilátero é:", area, "\b.")